// export const SET_INGREDIENTS = 'SET_INGREDIENTS';
// export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
// export const TEST = 'TEST';

export const PHOTOS_FETCH = 'PHOTOS_FETCH';
